export {default as Navigation} from './navigation/Navigation';
export {default as Chess} from './chess/Chess';
export {default as Aboutme} from './aboutme/Aboutme';
export {default as Display} from './display/Display'
export {default as Contact} from './contact/Contact'
export {default as Footer} from './footer/Footer'
export {default as StickyMenu} from './stickymenu/StickyMenu'
export {default as Chessdisplay} from './chessdisplay/Chessdisplay'
export {default as AboutMeMobile} from './aboutme-mobile/AboutMeMobile'